version: '3'

services:
    pokedexapp:
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        image: pokedex-docker
        container_name: pokedexapp
        restart: always # reiniciar el contenedor si se detiene
        ports:
            - "${PORT}:${PORT}"
        environment:
            MONGO_URI: ${MONGO_URI}
            PORT: ${PORT}
            DEFAULT_LIMIT: ${DEFAULT_LIMIT}

    db:
        image: mongo:5
        container_name: mongo-poke
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: nest-pokemons
        volumes:
            - ./mongo:/data/db